services:
  db:
    container_name: postgres
    image: postgres:17.2
    env_file:
      - ./.postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  avito-shop-service:
    container_name: avito-shop-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - ./.fastapi.env
    command:
      ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"]
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  postgres_data:
