services:
  db:
    container_name: postgres
    image: postgres:17.2
    env_file:
      - ./.postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  avito-shop-service:
    container_name: avito-shop-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.fastapi.env
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  postgres_data:
